config/routes.rb
P4know::Application.routes.draw do
  root to: 'home#index'

  post 'sessions/create'
  post 'sessions/destroy'

  post 'set_knowledge', to: 'things#set_knowledge'
  post 'get_knowledge', to: 'things#get_knowledge'

  resources :things, only: [] do
    get :autocomplete_thing_name, on: :collection, as: :autocomplete_names
  end
end

app/models/thing.rb
class Thing < ActiveRecord::Base
  has_and_belongs_to_many :users

  validates :name, presence: true, uniqueness: { case_sensitive: false }

  def self.from_string(thing_names)
    things = []

    thing_names.strip.gsub(/ +/, '').split(/,/).each do |thing_name|
      things.push(find_or_create_by(name: thing_name)) unless thing_name.blank?
    end

    things
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :things

  validates :name, presence: true, uniqueness: { case_sensitive: false }

  def authenticate(password)
    p4_login(name, password)
  end

  private

  def p4_login(username, password)
    result = `echo #{password} | p4 -p #{P4PORT} -u #{username} login`

    if (/User .* logged in./ =~ result)
      true
    else
      false
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :user_signed_in?

  def current_user
    User.find_by(id: session[:user])
  end

  def user_signed_in?
    current_user != nil
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # GET /
  def index
    render locals: {
      user_things:  set_user_things,
      results:      set_local_results
    }
  end

  private

  def set_user_things
    user_signed_in? ? current_user.things.sort_by { |e| e.name.downcase } : nil
  end

  def set_local_results
    results = Thing.from_string(session[:thing_names] || '')
    session[:thing_names] = nil
    results
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # POST /sessions/create
  def create
    @user = User.find_or_create_by(name: user_name_param)

    if @user.authenticate(user_password_param)
      session[:user] = @user

      flash[:info] = 'Logged in.'
      redirect_to :back
    else
      flash[:error] = 'Failed login attempt.'
      redirect_to :back
    end
  end

  # POST /sessions/destroy
  def destroy
    session[:user] = nil
    redirect_to :back, notice: 'Logged out.'
  end

  private

  def user_name_param
    params.require(:username)
  end

  def user_password_param
    params.require(:password)
  end
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController

  # before_action :authenticate_user!, only: [:set_knowledge]

  autocomplete :thing, :name, full: false

  # POST /set_knowledge
  def set_knowledge
    save_knowledge

    redirect_to :back
  end

  # GET /get_knowledge
  def get_knowledge
    session[:thing_names] = thing_params

    redirect_to :back
  end

  private

  def thing_params
    params.require(:thing_names)
  end

  def save_knowledge
    current_user.things << Thing.from_string(thing_params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_form.html.haml
.form-group.row
  .col-lg-12.col-md-12.col-sm-12.col-xs-12
    = autocomplete_field_tag :thing_names, '', autocomplete_names_things_path,
       'data-delimiter' => ', ', :multiple => true,
       class: 'form-control', width: '100%', disabled: disabled

app/views/home/index.html.haml
.row
  .col-lg-6.col-md-6.col-sm.6-col-xs-6
    .page-header
      %h2 I know...
  .col-lg-6.col-md-6.col-sm.6-col-xs-6
    .page-header
      %h2 Who knows...
.row
  .col-lg-6.col-md-6.col-sm.6-col-xs-6
    = form_tag set_knowledge_path, role: 'form' do
      = render :partial => 'home/form', locals: { disabled: !user_signed_in? }
  .col-lg-6.col-md-6.col-sm.6-col-xs-6
    = form_tag get_knowledge_path, role: 'form' do
      = render :partial => 'home/form', locals: { disabled: false }
.row
  .col-lg-6.col-md-6.col-sm.6-col-xs-6
    - if user_signed_in?
      - user_things.each do |thing|
        %h4
          %span.label.label-success
            = thing.name
  .col-lg-6.col-md-6.col-sm.6-col-xs-6
    - if results
      - results.each do |thing|
        .page-header
          %h4= thing.name
        - thing.users.each do |user|
          %h4
            %span.label.label-success
              = user.name

app/views/layouts/_flash_messages.html.haml
- if flash[:info]
  %div.alert.alert-info.alert-dismissable
    %button{ 'type' => 'button', 'class' => 'close', 'data-dismiss' => 'alert', 'aria-hidden' => 'true' }  &times;
    = flash[:info]
- elsif flash[:error]
  %div.alert.alert-danger.alert-dismissable
    %button{ 'type' => 'button', 'class' => 'close', 'data-dismiss' => 'alert', 'aria-hidden' => 'true' }  &times;
    = flash[:error]
- elsif flash[:notice]
  %div.alert.alert-warning.alert-dismissable
    %button{ 'type' => 'button', 'class' => 'close', 'data-dismiss' => 'alert', 'aria-hidden' => 'true' }  &times;
    = flash[:notice]

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default.navbar-fixed-top{ role: 'navigation' }
  .container-fluid
    .row
      .col-lg-8.col-md-8.col-sm-8.col-xs-8.col-lg-offset-2.col-md-offset-2.col-sm-offset-2.col-xs-offset-2
        .navbar-header
          .navbar-brand
            P4Know -
            = P4PORT
        .collapse.navbar-collapse
          %ul.nav.navbar-nav
          = render partial: 'sessions/form'

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title P4Know
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render :partial => 'layouts/navbar'
    .container-fluid{ style: 'padding-top: 50px;' }
      .row{ style: 'padding-top: 15px;' }
        .col-lg-8.col-md-8.col-sm-8.col-xs-8.col-lg-offset-2.col-md-offset-2.col-sm-offset-2.col-xs-offset-2
          = render :partial => 'layouts/flash_messages'
      .row
        .col-lg-8.col-md-8.col-sm-8.col-xs-8.col-lg-offset-2.col-md-offset-2.col-sm-offset-2.col-xs-offset-2
          = yield